golbang_jb/lib/models/participant.dart, golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_create2.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/event_update2.dart, golbang_jb/lib/pages/event/widgets/participant_dialog.dart, golbang_jb/lib/pages/profile/statistics_page.dart, golbang_jb/lib/provider/event/event_state_notifier_provider.dart, golbang_jb/lib/provider/participant/participant_service_provider.dart, golbang_jb/lib/provider/participant/participant_state_provider.dart
Issue: Resolved #45 
1. **Navigator.pop() 활용**: 이벤트 삭제 후 `Navigator.pop(true)`를 사용하여 삭제 성공 여부를 `EventPage`로 전달.
2. **결과 감지 및 목록 새로고침**: `EventPage`에서 `Navigator.push()`로부터 반환된 `true` 값을 확인하고, `setState()`와 함께 `_loadEventsForMonth()`를 호출하여 UI가 새로 고침되도록 처리.
3. **UI 강제 새로고침**: 이벤트 목록을 다시 불러온 후 `setState()`를 명시적으로 호출하여 즉시 반영되도록 함.
- 이벤트 삭제 -> 생성 -> 수정 순서
위 순서로 진행했을 때 UI에 바로 반영되는 모습을 확인해주시면 될 것 같습니다. 
https://github.com/user-attachments/assets/08d9f9b6-1bdc-4098-83e7-74a1e0547fff
before:
https://github.com/user-attachments/assets/d53c441b-b5de-425a-802c-2167d40a541c
after:
1. **`statusType` 필드 변경**: `Participant` 클래스에서 `statusType`을 `late final` 대신 일반 `String`으로 수정하여 한 번 초기화된 후에도 값을 업데이트할 수 있도록 변경.
2. **`copyWith` 메서드 활용**: `copyWith` 메서드를 사용해 `Participant` 객체의 `statusType`을 안전하게 업데이트하도록 변경하여, …
=> Feat&Fix: 이벤트, 참여자 상태 관리 기능 추가 & 이벤트, 통계 페이지 버그 해결

golbang_jb/lib/pages/event/event_create2.dart, golbang_jb/lib/pages/event/event_result_full_score_card.dart, golbang_jb/lib/pages/event/event_update2.dart, golbang_jb/lib/pages/event/widgets/group_card.dart, golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/pages/profile/statistics_page.dart, golbang_jb/lib/provider/statistics/statistics_provider.dart, golbang_jb/lib/services/group_service.dart, golbang_jb/lib/services/statistics_api.dart, golbang_jb/lib/services/statistics_service.dart, golbang_jb/lib/widgets/sections/member_dialog.dart, golbang_jb/pubspec.lock, golbang_jb/pubspec.yaml
> ex) #이슈번호, #이슈번호
- Resolved #59 - 통계 데이터 버그 해결
- [[API] 기간별 통계 조회시 제대로 잘 동작하지 않는 버그 해결 → 상태관리 추가](https://learntosurf.notion.site/API-11281c5c2178810d96ade86df9f549e1?pvs=4)
- [[생성] 멤버 초대 시 전체 유저 리스트에서 검색 되는 기능이 추가되어야 함](https://learntosurf.notion.site/11281c5c217881768018cce4e575fac6?pvs=4)
- [전체적으로 보라색 글씨는 흰색으로 바꾸어 가독성 높이기 (스코어카드 포함)](https://learntosurf.notion.site/11281c5c217881b1b6d1c2e23d84982c?pvs=4)
> **모임 생성 페이지**
- 1d3b6a911096608de57a4aef8398ee21e5cddc39: 모임 생성 페이지에서 멤버 추가 시 전체 유저 리스트에서 검색되는 기능을 추가했습니다. 
https://github.com/user-attachments/assets/6fa83e24-8dd1-42b0-a4e9-d7aa9ff2e390
> **이벤트 결과 페이지**
- 20c08adfe35f2a94b10d28df331bcdc75c68814d: **이벤트 결과 스코어 정보를 엑셀로 저장**하는 기능을 추가했습니다. 
- 이 기능은 중범선배(@Kojungbeom )가 이어받아 만들어진 엑셀을 (저장하는 게 아니고) 사용자의 이메일로 보내주는 …
=> Fix: 통계 페이지 버그 수정 및 상태 관리 추가 & Feat: 모임 생성 시 유저 검색 기능 추가

golbang_jb/lib/models/group.dart, golbang_jb/lib/pages/group/group_main.dart, golbang_jb/lib/pages/profile/statistics_page.dart, golbang_jb/lib/pages/profile/user_info_page.dart, golbang_jb/lib/widgets/sections/group_item.dart
> Resolved #77 - Production Review에서 발생한 버그 해결, #78
- [내 정보 - 프로필 이미지 위에 X 표시가 보통 다른 앱에도 있는지? → 확인이 필요함 ⇒ 없으면 프로필 이미지 지우기 라는 버튼으로 대체
](https://learntosurf.notion.site/X-dae2a419d9a14d069736954e75ecbfaf?pvs=4)
- [모임 메인 - 관리자인 경우 모임이름 밑에 관리자라는 텍스트 추가](https://learntosurf.notion.site/46c898cc1f334ca89720f07fb1d053b1?pvs=4)
- [통계  - 모임별랭킹 오버플로우 에러 해결](https://learntosurf.notion.site/da853b8976e14ca38567ba316b7e3370?pvs=4)
- [통계 - 기간별 조회 기능 디버깅](https://learntosurf.notion.site/086f71b50dcf4148a6bf9fe4b54de590?pvs=4)
- [모임 메인 - 모임 이름 오버플로우 에러 디버깅](https://learntosurf.notion.site/d82845634122440bb6089fd71dbbba30?pvs=4)
> 모임
- 9c1ef5f62c59a0e224a3e47d75fadbbd97b00885: 관리자인 경우 모임이름 밑에 관리자라는 텍스트 추가하기 위해 isAdmin 요소 모델에 추가
- 7c74e0c40757059a9b39c9ca7e24ce7f36c1e8d0: 모임 메인 - 관리자인 …
=> Fix&Feat: Product Review에서 발생한 버그 해결, 수정해야 할 디자인 및 기능 추가

golbang_jb/lib/models/profile/club_profile.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/event/event_result.dart, golbang_jb/lib/pages/event/widgets/team_result.dart, golbang_jb/lib/pages/game/score_card_page.dart
- [event_main에서 결과 조회/게임 시작 페이지 이동 (+게임 시작 전 새로 추가)](https://www.notion.so/learntosurf/a9301bb2143d48c1ba4af37c51158a48?pvs=4)
- [이벤트 전체 결과 화면 - Total Score를 Total Stroke으로 교체](https://www.notion.so/learntosurf/Total-Score-Total-Stroke-ee33c7df4df749d9954401edf764f40e?pvs=4)
- [게임 시작 화면에서 -디폴트 이미지 변경 ⇒ 기본 이미지로](https://www.notion.so/learntosurf/9317f2c4b9fb4818bcf8d66fb9c1b835?pvs=4)
event_main에서 결과 조회/게임 시작 페이지 이동하는 on_pressed 부분 수정
jungbeom 계정으로 11/29일 이벤트가 3개 중에 2개가 사진처럼 에러 발생
이 외에도 스코어 카드 기록 후, 이벤트 수정시 에러 발생하여
게임 시작 전에는 게임시작 버튼이 안뜨도록 비활성화하였고, 
게임 시작 후에는 이벤트 수정이 불가능하도록 하였습니다.
const가 누락된 부분들에 모두 추가해주었고,
DateTime.now()의 경우, 여러 위젯에서 같은 변수를 사용하지 않고, 모두 다른 DateTime.now()를 호출해서 사용하고 있어서
이 부분 역시 수정했습니다. 추가로 1초마다 DateTime.now()를 불러오도록 했습니다.
이벤트 결과조회 디버깅
=> Feat&Refactor: 페이지 이동 로직 추가 및 디자인/현재 시각 로직 리펙토링

golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/group/group_create.dart, golbang_jb/lib/pages/group/group_main.dart, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/pages/signup/additional_info.dart, golbang_jb/lib/widgets/sections/member_dialog.dart
> Resolved #77, Resolved #78, Resolved #84
- [이벤트 결과 화면 (코스 정보 코드 다시 추가)](https://learntosurf.notion.site/f7a9ca78641042d0a79e16389f26f9bd?pvs=4)
- [모임 생성 - 유저 조회 시 한 번에 다 조회하지 않고 정렬한 데이터 페이지네이션 하기(스크롤 할 때마다 Fetch) ⇒ 그냥 검색되도록 수정](https://learntosurf.notion.site/Fetch-a31e25d71c5341ad82bbd9b133b63f94?pvs=4)
- [모임 검색시 오버 플로우 에러](https://learntosurf.notion.site/71aec12369a74a16b10c47f45eaffae6?pvs=4)
- [모임 메인 페이지에서 이벤트 페이지가 어디있는지 구체적으로 적어주기 (달력을 클릭해서 일정을 만들어주세요)](https://learntosurf.notion.site/53b7f9cfe45c4117b08d33497617578d?pvs=4)
- 493cff1fa796cc846e9c12ca98a1766f640f1a7b: 모임 생성 페이지에서 멤버 추가 다이얼로그에서 유저 조회시, 유저 목록이 보이는 것 대신에 검색되도록 수정했습니다. 단, 관리자 추가시에는 멤버 목록으로 필터링되어 목록이 보이도록 수정했습니다.
관련 영상 함께 첨부합니다.
> 이벤트 결과 조회
- 3ccefcf434f3fa69cf4784d0cbdd9e37b9071d36: 이벤트 결과 화면에 코스 …
=> Feat&Fix: 코스 정보 디자인 코드 복구, 모임 생성-유저검색, 모임 메인-오버플로우해결&안내메세지 수정

golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/widgets/ranking_list.dart, golbang_jb/lib/pages/event/widgets/user_profile.dart, golbang_jb/lib/pages/game/overall_score_page.dart, golbang_jb/lib/pages/group/group_main.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/pages/notification/notification_history_page.dart, golbang_jb/lib/widgets/sections/upcoming_events.dart
아직 전부 완성하진 못했는데 구노 작업 전에 먼저 Pull 할 수 있도록 PR 올려둡니다. 
- 홈화면 아무것도 없을 때 문구 추가하는 거는 아직 에러가 나서 진행 중 입니다.
- 스코어카드 디자인은 아직 안했습니다. 
> [해당 노션 링크에 귀가 후 정리해뒀던거 올리도록 하겠습니다.](https://learntosurf.notion.site/e9f6330812874668a37e3874ad98dcbe?pvs=4)
- 이메일 안보냈는데 보내졌다고 메세지 나오는 이슈
- 성공시에는 굳이 Snackbar 안띄우고 실패시에만 띄우도록 변경함
- 이벤트 결과 조회에서 아이콘 대체
- 모두 flutter person 아이콘으로 대체하였습니다.
-  모임 목록 한 화면에 9개로 바꾸기 
- 한 화면에 다 담기 위해 항목별 세로 간격하고, sizebox 크기 조정하였습니다.
- 알림 페이지 골방 Text logo로 변경
=> Hotfix: 이메일 Snackbar 알림 이슈, 이벤트 결과페이지 아이콘 대체, 모임 목록 개수 변경, 알림 페이지 타이틀 골방 텍스트 로고로 변경

golbang_jb/android/app/build.gradle
- 구글맵 안나오던 이슈
https://console.cloud.google.com/apis/credentials/key/852153cd-b4be-417c-9ed0-99e5261eb296?inv=1&invt=AbmYjQ&project=golbang-test-31a73
다들 링크에 따라서 디버깅 서명 등록해주셔야 합니다. (릴리즈 서명은 제가 추가함)
- 기존에는 env에서 google map API를 읽어오도록 돼있었는데, 확인해보니 못읽어 오고 있더라구요. 
- 그래서, 제가 [참고한 blog](https://velog.io/@ghenmaru/Flutter-google-map-API-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-%ED%98%84%EC%9E%AC-%EC%9C%84%EC%B9%98%EB%A1%9C-%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B0)를 따라하다 보니 local.properties에 구글 맵 API키를 저장하고 불러오게끔 진행하였습니다.
- 그리고 이전에는 못읽으면, null대신 default API key가 읽어졌는데, 이제는 API키 없으면 에러 뜨도록 조치하였습니다.
`디스코드-아카이브-앱 릴리즈용 파일`에서 local.properties 참고해주세용.
=> refactor: env가 아닌 기존의 localProperties에서 API키 읽어오도록 변경

golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/game/score_card_page.dart
[fix&refactor: 불참 인원은 스코어 카드에 안보이도록 수정 및 screenSize 프로바이더 사용하도록 수정](https://github.com/iNESlab/Golbang_FE/commit/b6b1b74ce0ad0a4894c46ec27f4dce7fb0b1fd20)
- 게임 스코어 카드에 들어가면, 서버에서는 프론트에서 주는대로 모두 입력하기 때문에, 프론트에서 걸러야 했음.
- 먼저, 스코어 카드에서 필터링으로 제외
- 겸사겸사 screenSize도 riverpod를 사용하도록 수정
[fix&refactor&bug: 불참 인원은 게임 시작 버튼 비활성화 but 비활성화 해도 색상 변경이 안됨](https://github.com/iNESlab/Golbang_FE/commit/b8b5c7f6ca33293f7c9ca1ae6a97b5978ec4ecae)
- 불참인원들이 점수를 수정할 수 있으므로 이벤트 상세나 메인 같은 페이지에서 접근을 못하도록 함
- 다만, 사진처럼 비활성화가 되더라도 차이가 없음. 
- 다르게 하려면 할 수는 있는데, 이미 불참으로 색상이 강하게 표시돼있고,
현재 코드 구조로는 중복되는 코드가 발생하고 이벤트 메인이다 보니 렌더링 처리할 것도 많아서 일단 그대로 둠
[fix: 불참 인원은 게임 시작 버튼이 아이에 안보이도록 함](https://github.com/iNESlab/Golbang_FE/commit/784821e344a9217d5fc4c53dc7887f966c8e8e73)
- 이벤트 상세는 코드 중복 없이도 가능한 구조라 안보이도록 제외함.
비활활성화 해도 색상이 …
=> Fix: 스코어 카드 에러 최종 수정

golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/game/overall_score_page.dart, golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/utils/reponsive_utils.dart, golbang_jb/lib/widgets/common/section_with_scroll.dart, golbang_jb/lib/widgets/sections/bookmark_section.dart, golbang_jb/lib/widgets/sections/groups_section.dart, golbang_jb/lib/widgets/sections/upcoming_events.dart
- 앱스토어 심사역들은 아이패드로 심사한다고 함 (Reject letter를 확인해보면 우리 앱 심사역도 마찬가지)
- 아이패드는 고려하지 않았어서 적응형 레이아웃 적용이 안되어있음.
- 아이패드 미지원 시에는 빌드할 때 리스트에서 빼고 올리면 된다고 함.
- 이에 화면의 너비 및 상태 (가로모드, 세로모드) 폰트 사이즈를 조정함. (글자크기는 그대로 둔 상태에서 더 많은 요소를 보여주는 방식이 더 적절할 수도 있음..)
- 가로모드일 경우 변경되어야 할 사항이 많고 레이아웃을 잡기 힘들어서 우선은 세로모드로 고정하는게 좋을 것 같음.
- 수정된 페이지: HomePage, EventMain, EventDetail, ScoreCardPage, OverallScorePage
- utils 폴더에 responsive_utils.dart에 ResponsiveUtils 클래스로 만들어 폰트사이즈를 관리하는 방식으로 수정함.
=> [hotfix] 적응형 레이아웃 및 폰트사이즈 조정

golbang_jb/ios/Runner/Info.plist, golbang_jb/lib/pages/common/privacy_policy_page.dart, golbang_jb/pubspec.yaml
- [build: iOS 빌드 시 암호화문서 제출하지 않아도 되도록 처리](https://github.com/iNESlab/Golbang_FE/commit/9e13d41aca197964a0773a12026d3bc2912f15a1): 수출 규정 관련 문서 누락 문제를 해결하기 위해 해당 코드를 추가함
- [fix: 개인정보처리방침 내의 선택항목에 전화번호와 생년월일 추가](https://github.com/iNESlab/Golbang_FE/commit/59e78a3b273b6923713f91b7a1d636999e5a3d3e): iOS 심사 거절 사유 중 하나(`핵심기능과 관련 없는 전화번호와 생년월일을 필수로 요구`)를 해결하기 위해 개인정보처리방침 수정
- 사이트에 있는 개인정보처리방침도 수정 완료된 상태입니다.
- [build: 앱번들 버전 수정](https://github.com/iNESlab/Golbang_FE/commit/6ede210fc9c5ad98bd1f3ffdb9490efb2241cbf3): 앱 번들 버전은 현재 21인 상태입니다. 혹여나 다른 분들이 저처럼 하나하나 빌드하시지 않도록 함께 올립니다.
- 안드로이드 앱 번들을 올린 후, iOS 앱 번들을 올렸기 때문에 로그인항목에 디폴트 값(`Kojungbeom`)이 들어가 있지 않은 상태인 점 참고해주세요
=> [iOS 빌드 최적화 및 개인정보처리방침 수정] iOS 심사 대응 및 빌드 프로세스 개선

golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/pages/profile/statistics_page.dart
구글 플레이 비공개 테스트 업데이트 (1.0.0+23, 1.0.0+24)
- 통계 페이지 버튼 간격 조정
- 홈 화면 "다가오는 이벤트" 날짜에 따라 내림차순으로 변경
- 이벤트 생성 페이지에서 장소 선택 후 변경 시 구글맵 위치 반영이 안되었던 이슈 해결
=> [Fix] 통계 페이지 버튼 간격, 홈 화면 다가오는 이벤트 정렬 방식 & 구글맵 장소 변경시 반영 안되었던 이슈 해결

golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/community/member_manage_page.dart, golbang_jb/lib/pages/community/member_settings_page.dart, golbang_jb/lib/pages/group/group_create.dart, golbang_jb/lib/services/club_service.dart, golbang_jb/lib/services/group_service.dart, golbang_jb/lib/widgets/sections/member_dialog.dart
[feat: 클럽 멤버 초대 API연동](https://github.com/iNESlab/Golbang_FE/commit/8264c6796b1c69d2fca3fa7b4e07a38ca717373d)
- 초대후, 멤버 조회 API를 재실행시키도록 하였습니다~ (새로 초대된 유저도 바로 반영되도록 했어요)
[fix: print->log로 변경 및 profileImage는 Nullable이 아니라서, startsWith로 변경](https://github.com/iNESlab/Golbang_FE/commit/4364f0c7878fafce91ba0c1cce655f0eb6fa8cd0)
- flutter에서는 print문을 지양하라해서, log로 전환했습니다! 앞으로 Log 애용해주세요~
- 대부분의 profileImage가 null로 오면, `''` 이렇게 받도록 변형시켰기 때문에, `profileImage != null ? :` 문법이 안됩니다!
startsWith('https') 애용해주세요~
[refactor: group_service의 클럽 멤버 초대 API를 club_service로 이동 및 리스트 전송으로 변경](https://github.com/iNESlab/Golbang_FE/commit/ec2e5b1d3212e829ecdcc3b2eb960c7e0a976259)
- 이전에 group_service를 club_service로 통합하기로 했어서, API가 동일한게 있길래 겸사겸사 진행하였습니다
[delete: 지금까지 onMemberSelected가 사용이 안되고 있어서 주석처리 및 …
=> feat: 클럽 회원 초대 API 연동

golbang_jb/lib/models/responseDTO/CourseResopnseDTO.dart
[Fix: CourseResposneDTO: pars null safe처리](https://github.com/iNESlab/Golbang_FE/pull/129/commits/5b8ac09c6ab36a5f24fd4043804206c6b889eafc) 
[5b8ac09](https://github.com/iNESlab/Golbang_FE/pull/129/commits/5b8ac09c6ab36a5f24fd4043804206c6b889eafc)
- pars까지 응답하는 API랑 아닌 API가 둘 다 있음
- 그래서, pars가 null일 경우, 빈 배열로 바꿔주도록 수정
=> Fix: CourseResposneDTO: pars null safe처리

golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/game/overall_score_page.dart, golbang_jb/lib/provider/event/game_in_progress_provider.dart
> [feat(eventCreate): 이벤트 생성 시 "관리자만 모임을 선택할 수 있다"는 안내 문구 추가](https://github.com/iNESlab/Golbang_FE/commit/a83e2dfecb42ece437560c9c3d29a516b687e7a7)
- **Before**: 관리자 권한이 없고 앱을 처음 사용하는 사용자가 이벤트를 생성하려고 하면 실패 이유를 알 수 없었습니다. 
- **After**: 이벤트 생성 화면에서, “`자신이 관리자인 모임만 이벤트를 생성할 수 있습니다.`” 라는 안내 문구를 추가했습니다.
> [feat(game-ranking): 게임 진행 시 점수 표기 안내 다이알로그 추가](https://github.com/iNESlab/Golbang_FE/commit/eddccff056030efb68c23db6c1737f3025f7f21c)
- **Before**: 랭킹 조회 화면에서 표기되는 점수(“+1 (14)”)가 무엇을 의미하는지 모르는 사용자가 있었습니다. 
- **After**: [점수 표기 안내] 버튼을 누르면 다이얼로그가 떠서
- “+1”: 방금 친 홀에서 기록한 점수
- “(14)”: 지금까지의 누적 스코어
라고 알려주도록 했습니다.
**내용**:
```dart
'골프 스코어는 두 가지 숫자로 표기됩니다.\n\n'
'예) "+1 (14)"\n'
'• "+1": 방금 친 홀에서 기록한 점수\n'
'• "(14)": 지금까지의 누적 스코어\n\n'
'즉, 괄호 안의 숫자가 전체 합계 점수이며, 앞쪽의 숫자는 마지막 홀에서 친 점수를 의미합니다.',
```
> …
=> Feat: Event Create - 관리자 안내 문구 추가, Game-Ranking - 점수 표기 안내 다이얼로그, Event & EventDetail 게임 진행 상태 관리

golbang_jb/lib/pages/event/event_create2.dart, golbang_jb/lib/pages/event/event_update2.dart
- 참가자를 모두 선택하지 않아도 완료 버튼 활성화
- 미선택된 활성화는 1조 혹은 A팀 1조로 지정됨(안내문 수정)
- (bug) 이전 이벤트가 팀전일 경우, 참가자 조회가 바로 안됨(조 생성 눌러야 함)
..... 팀전, 개인전, 조 이동, 팀 이동 정말 다양하게 테스트를 진행하였고... 확인된 버그는 저거 한개입니다...
=> Fix&Bug: 이벤트 수정 기능

golbang_jb/lib/services/club_service.dart, golbang_jb/pubspec.lock
[feat(club): 관리자 기능은 API URL에 admin이 들어가도록 추가(모임 삭제, 멤버 초대, 멤버 강퇴)](https://github.com/iNESlab/Golbang_FE/commit/8a59d39076d0254463640a1b34679ed1a05fc5af)
- 관리자 기능 중 모임 수정 API를 작업하며 API prefix에 `admin`을 추가하게 되었습니다
- 이에 관리자 기능으로 작동하는 모임 삭제, 멤버 초대, 멤버 강퇴 API에 `admin` 을 추가하였습니다.
>[!WARNING]
> **멤버 초대 시, 안드로이드에서 ClubMember pk로 보내는지 User pk 보내는지 체크가 필요합니다**
>[!WARNING]
> **멤버 강퇴 기능이 작동하지 않습니다. API 호출 전 다이알로그가 뜨지 않습니다.**
=> Feat&Bug: 관리자 기능은 API URL에 admin이 들어가도록 추가(모임 삭제, 멤버 초대, 멤버 강퇴)]

golbang_jb/lib/pages/club/club_create_page.dart, golbang_jb/lib/pages/club/club_edit_page.dart, golbang_jb/lib/pages/club/club_main.dart, golbang_jb/lib/pages/community/admin_settings_page.dart, golbang_jb/lib/pages/event/event_main.dart
- **Before:** 프론트엔드와 백엔드 모델 모두에서 설명 필드를 nullable 처리하였음에도, 설명 미입력 시 생성 불가 오류가 발생하는 문제
-  **After**: 이제 설명 입력은 선택 사항이며, 설명 없이도 모임을 생성 및 수정할 수 있음
모임 생성 / 모임 수정
- **Before**: 사용자들이 일정 생성하라는 안내 텍스트를 보고 바로 일정을 생성합니다. 하지만 모임을 존재해야 일정을 만들 수 있으므로 사용자들이 이를 인식하기까지 시간이 걸립니다. 
- **After**: 이를 해결하기 위해 사용자가 일정 추가 버튼을 눌렀을 때, 참여 중인 모임이 없는 경우 “모임이 없어요. 먼저 모임을 만들어 주세요.”라는 안내 메시지를 표시하도록 수정하였습니다.
> [!TIP]
> - 텍스트: 
>    - 모임이 없을 경우: `참여 중인 모임이 없어요. 먼저 모임에 참여하시거나 새로운 모임을 만들어주세요.`
>    -  모임은 있지만 일정이 없는 경우(=기존): `일정 추가 버튼을 눌러 이벤트를 만들어보세요.`
>    <img width="200" alt="스크린샷 2025-03-24 오전 1 39 13" src="https://github.com/user-attachments/assets/23cf32b4-0a29-412b-8a76-86285ef923bb" /> <img width="200" alt="스크린샷 2025-03-24 오전 1 40 39" src="https://github.com/user-attachments/assets/85b3f8c8-1646-405 …
=> Feat&BugFix: 모임 상태 업데이트 및 UI/UX 개선 - 모임 생성/삭제, 이벤트 안내 메시지 수정

golbang_jb/lib/pages/club/club_main.dart, golbang_jb/lib/pages/community/community_main.dart, golbang_jb/lib/provider/club/club_state_provider.dart, golbang_jb/lib/widgets/sections/groups_section.dart
[Fix: provider selectedClub 수정](https://github.com/iNESlab/Golbang_FE/commit/0e521ba107b339ae63a624d74caa9c71160072e3) 
- provider selected club이 외부 주입이였음
- 이는 구독중인 clubs와 별개의 존재라 멤버를 수정해도 반영이 안됐음
- 그래서, Id를 기준으로 club을 찾도록 변경
[Refactor: 커뮤니티에서 뒤로가기시, 속한 모임 재 조회 및 상태 구독](https://github.com/iNESlab/Golbang_FE/commit/1a8c383d7515ea324d05d0d94f450b9a903423eb) 
- PopScope의 이해가 낮아 일단 임시 조치로 이렇게 했습니다.
PopScope 이해도가 높으면 코드가 좀. 바뀔수도 있어요
iOS는 자체 폰 뒤로가기를 모르겠어서, 커뮤니티 메인에서 뒤로가기시
Club 조회 API가 호출되는지 확인을 못했습니다..
=> Fix: 클럽 메인화면에서 community이동시, 멤버 수정내역이 반영이 안되던 문제

golbang_jb/lib/models/event.dart, golbang_jb/lib/models/hole_score.dart, golbang_jb/lib/models/participant.dart, golbang_jb/lib/models/profile/get_event_result_participants_ranks.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_result_full_score_card.dart, golbang_jb/lib/pages/event/widgets/mini_score_card.dart
**[Fix: score, sum_score, handicap_score, rank, handicap_rank 중 null값이 올 수 있도록, null 처리 로직 추가](https://github.com/iNESlab/Golbang_FE/commit/832d2a0ff8e720363347f27593f47f0816ff6ae9)**
- **Before**: 아래 사진과 같이 `이벤트 결과 조회`시 로딩 화면이 계속 뜨고 아래 에러가 발생했습니다.
`E/flutter (11848): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int`
- **원인**: 
- 지난 주, 스코어에 0도 유효한 값이기에 입력하지 않은 값을 Null로 처리하는 방식으로 수정하였습니다. 
- 이에 웹소켓 스코어 입력 페이지는 반영되었지만 연쇄적인 다른 페이지에서는 스코어, `sum_score`, `handicap_score`, `rank` 등 `Null`로 오는 정보에 대한 처리가 없었습니다.
- **After**: 
- 한 줄씩 테스트해가며 꼭 필요한 부분 위주로 `Null` 처리 로직 추가하였습니다. 
- 그 결과 아래 이미지처럼 다시 이벤트 결과 조회 페이지가 정상적으로 로딩되는 것을 확인해볼 수 있습니다.
**[Fix: Full Score Care 페이지가 넘칠 경우 발생하는 크래시 …
=> fix/UI: 이벤트 결과 Null 처리, Full Score Card 스크롤 추가 & 이메일 아이콘 교체

golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/event_update2.dart, golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/services/bio_auth.dart
- 스코어카드 레이아웃 및 재연결 로직 수정
- 백그라운드에서 포그라운드로 돌아올 때 재연결 시도
- 웹소켓 메세지 수신이 제대로 안될 경우 뒤로가기 팝업창 생성
- 레이아웃 박사님 요청사항에 맞게 변경
- 이벤트 생성 및 수정에서 종료날짜를 시작날짜 이틀뒤로 자동설정
=> Fix: 스코어카드 레이아웃, 재연결 로직 수정 및 이벤트 종료날짜 자동설정

golbang_jb/android/.gitignore, golbang_jb/lib/global/PrivateClient.dart, golbang_jb/lib/global/PublicClient.dart, golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/community/member_manage_page.dart, golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/widgets/participant_dialog.dart, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/pages/logins/widgets/forgot_password.dart, golbang_jb/lib/pages/logins/widgets/social_login_widgets.dart, golbang_jb/lib/pages/profile/profile_screen.dart, golbang_jb/lib/pages/profile/statistics_page.dart, golbang_jb/lib/pages/signup/additional_info.dart, golbang_jb/lib/pages/signup/signup.dart, golbang_jb/lib/provider/auth/auth_provider.dart, golbang_jb/lib/services/auth_service.dart, golbang_jb/lib/services/bio_auth.dart, golbang_jb/lib/services/club_member_service.dart, golbang_jb/lib/services/club_service.dart, golbang_jb/lib/services/event_service.dart, golbang_jb/lib/services/feedback_service.dart, golbang_jb/lib/services/group_service.dart, golbang_jb/lib/services/notification_service.dart, golbang_jb/lib/services/participant_service.dart, golbang_jb/lib/services/statistics_service.dart, golbang_jb/lib/services/user_service.dart, golbang_jb/lib/utils/email.dart, golbang_jb/lib/utils/excelFile.dart
- 아래 회의록에서, 수정하기로 한 사항
- https://www.notion.so/1ef8b9c13e4b808f8fb0eaa14bc3e574?pvs=4
[refactor: dio에서 서버 domain 관리](https://github.com/iNESlab/Golbang_FE/commit/85570f09009f7d47f1a3cb3149d6c9fabfbd5697) 
- print -> log 변경
- 통계(시작일-종료일) API 버그 수정
- 비밀번호 초기화 snackbar 안나오는 버그 수정
- 팀전 게임 결과 조회 테스트 안함
[refactor: 종료일이 시작일 +1이 되도록 변경](https://github.com/iNESlab/Golbang_FE/commit/d97b9448024e6449b946716f4ccb1a9259358965)
[feat: 참가자 전체 선택 버튼 추가](https://github.com/iNESlab/Golbang_FE/commit/f921149b4490ecf92562c5cb62e5b18e0dbee439)
[refactor&design: 이메일 전송/엑셀 작성 로직 util로 분리 및 이벤트 참가자 조회 디자인 변경](https://github.com/iNESlab/Golbang_FE/commit/7a52527d0f30183e87241235f91f94181551806c)
[refactor: 자동로그인 -> 재로그인으로 변경](https://github.com/iNESlab/Golbang_FE/commit/b8e7b6fe0c317709353028 …
=> refactor: 번개미팅 수정 1
