golbang_jb/lib/models/create_event.dart, golbang_jb/lib/models/event.dart, golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_create2.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/event/event_result.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/event_update2.dart, golbang_jb/lib/pages/event/widgets/location_search_dialog.dart, golbang_jb/lib/pages/event/widgets/no_api_participant_dialog.dart, golbang_jb/lib/pages/event/widgets/toggle_bottons.dart, golbang_jb/lib/widgets/sections/upcoming_events.dart
장소이름의 경우, 서버 PR까지 새로 받으셔야 합니다.
=> Refactor: 이벤트 1순위 피드백(2순위 피드백 일부 포함) 

golbang_jb/android/app/src/main/AndroidManifest.xml, golbang_jb/lib/main.dart, golbang_jb/lib/pages/event/event_result_full_score_card.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/services/auth_service.dart, golbang_jb/pubspec.lock, golbang_jb/pubspec.yaml
아래 내용들 관련하여 노션 작성하여 공유하도록 하겠습니다..!
- Excel 파일 이메일 전송 기능 (In progress)
- FCM 토큰 로그인시 백엔드로 전송하는 방식으로 교체
- FCM 메세지 감지를 위한 핸들러 생성 (In progress)
---
- Foreground에서 상태에서 메세지 받을시 감지는 하지만 푸시알람을 띄우지 못하고 있음
- Background 상태에서도 감지는 하지만 시스템 알림을 띄우지 못하고 있음 (Permission하고 Flutter notification 썼지만 되지않았음)
=> Hotfix: FCM 토큰 검사 로직 로그인시로 변경 & Excel 파일 이메일 전송 기능 및 메세지 핸들러 생성 (In progress)

golbang_jb/lib/pages/group/group_main.dart
- https://learntosurf.notion.site/UI-316c2ea022324d22aa06d867e89d5310?pvs=4
- 모임 메인 페이지에서 모임명 검색 기능 추가
=> Hotfix(feat): 모임 메인 페이지에서 모임명 검색 기능 추가

golbang_jb/lib/pages/event/widgets/group_card.dart, golbang_jb/lib/pages/logins/widgets/login_widgets.dart
- 참가자를 `각 조에 추가하는 버튼`을 `상단의 조 이름`과 통합시켰습니다.
- 로그인시 비밀번호 visible 클릭해도 안보이던 문제 수정했습니다.
=> Design: 이벤트 조원 추가 버튼 위젯 디자인 수정

golbang_jb/lib/widgets/sections/member_dialog.dart, golbang_jb/pubspec.lock
- 모임 생성시, 유저 초대하는 검색창을 이벤트 생성시 초대하는 검색창과 UI를 통일시켰습니다.
=> Hotfix: 참가자 초대창 UI 수정

golbang_jb/android/app/build.gradle, golbang_jb/android/app/google-services.json, golbang_jb/android/app/src/main/AndroidManifest.xml, golbang_jb/android/build.gradle, golbang_jb/android/settings.gradle, golbang_jb/assets/config/.env, golbang_jb/ios/Runner/Info.plist, golbang_jb/lib/main.dart, golbang_jb/lib/pages/event/event_result_full_score_card.dart, golbang_jb/lib/pages/group/group_main.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/services/group_service.dart, golbang_jb/lib/services/user_service.dart, golbang_jb/pubspec.lock
늦게 올려 죄송합니다..
https://learntosurf.notion.site/20241112-Progress-4f65aa65860a4b13bc00aa09367ce8b7?pvs=4
- Notification 알림 클릭시 동작 수정
-  해당 모임의 커뮤니티 페이지로 가지도록 수정함
- 로그인이 된 상태인지를 체크하는 함수를 생성하여 앱이 Background에서 동작 시에 로그인을 거치지 않도록 함
- 임시로 AccessToken이 있는지 여부를 체크하여 로그인 여부를 판단하도록 만듬.
- 나중에 App을 다시 킬 때도 이를 활용하여 로그인없이 바로 켜지도록 해도 괜찮을 듯. 
- 엑셀파일 용 Transpose 함수 생성했는데 아직 적용은 안함 (보완해야 할 점 참고)
```dart
List<List<dynamic>> transpose(List<List<dynamic>> data) {
if (data.isEmpty) return [];
return List.generate(
data[0].length,
(colIndex) => List.generate(data.length, (rowIndex) => data[rowIndex][colIndex]),
);
}
```
```dart
// 로그인 여부 확인 (임시)
Future<bool> isLoggedIn() async {
final accessToken = await storage.readAccessToken();
return accessToken != null && accessToken.isNotEmpty;
}
```
---
- 현재 …
=> Fix: Foreground/background notification 기능 정상화

golbang_jb/lib/main.dart, golbang_jb/lib/models/club_member.dart, golbang_jb/lib/models/group.dart, golbang_jb/lib/pages/community/community_main.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/group/group_main.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/pages/logins/widgets/login_widgets.dart, golbang_jb/lib/services/group_service.dart, golbang_jb/lib/services/user_service.dart, golbang_jb/lib/widgets/sections/bookmark_section.dart, golbang_jb/lib/widgets/sections/groups_section.dart, golbang_jb/lib/widgets/sections/upcoming_events.dart, golbang_jb/pubspec.lock, golbang_jb/pubspec.yaml
> ex) #이슈번호, #이슈번호
- 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 설명에 커밋 번호도 있다면 도움이 됩니다.
아래 내용 중 수정된 부분 위주로 작성해주세요! (수정되지 않는 부분은 지워주시면 됩니다)
1. 커뮤니티 메인에 관리자 이름 출력
2. 로그인시 소셜 로그인 삭제
3. 즐겨찾기 api 연결
4. 이벤트 공유기능
1.즐겨찾기 ui 크기 수정
---
1. 이벤트 링크 생성 
2. 한글 입력 시 깨짐 현상
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> Feat: 프론트 수정

golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/services/statistics_service.dart
1. 즐겨찾기 api 예외처리
> ex) #이슈번호, #이슈번호
- 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 설명에 커밋 번호도 있다면 도움이 됩니다.
아래 내용 중 수정된 부분 위주로 작성해주세요! (수정되지 않는 부분은 지워주시면 됩니다)
1.  즐겨찾기 예외처리 추가
---
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> Feat: 즐겨찾기 예외처리 추가

golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/group/group_main.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/pages/home/splash_screen.dart
- https://www.notion.so/learntosurf/Golbang-Font-7e91ec35d37f4b7b8c291a70cf2f91cb?pvs=4
- https://www.notion.so/learntosurf/bbadce637ad64782833358dec926afd2?pvs=4
=> Fix: 이벤트 수정 페이지 다음버튼 활성화 및 스플래시 페이지 수정

golbang_jb/lib/pages/community/admin_settings_page.dart, golbang_jb/lib/pages/community/community_main.dart, golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/community/member_manage_page.dart, golbang_jb/lib/pages/community/member_settings_page.dart, golbang_jb/lib/pages/group/group_main.dart, golbang_jb/lib/pages/notification/notification_history_page.dart, golbang_jb/lib/pages/signup/additional_info.dart, golbang_jb/lib/services/club_service.dart, golbang_jb/lib/services/event_service.dart, golbang_jb/lib/services/notification_service.dart, golbang_jb/lib/widgets/sections/groups_section.dart, golbang_jb/pubspec.yaml
https://learntosurf.notion.site/1129-Progress-18064a08d336466ebf1049d7da51205c?pvs=4
=> Fix&Feat: 알림 히스토리 페이지 수정 및 모임 설정 페이지 임시 제작

golbang_jb/android/settings.gradle, golbang_jb/pubspec.yaml
- [릴리즈 배포](https://learntosurf.notion.site/521cad5404b4435d8bf47ba3f8dbcd68?pvs=4)
- 자세한 내용은 노션 참고해주세요
https://tmd8633.tistory.com/39
---
실제 폰으로 보니, 전체적으로 위젯이 다 큽니다.
그런데, 다시 보니 위젯이 크다기보다는 한 화면에 너무 이것저것 많이 나와있는 문제도 있어보여서
사용자의 동작에 따라 다른 위젯은 off되는 등의 기능이 추가되면 좋을 것 같아요.
(홈에서는 아래 슬라이드시, 즐겨찾기 및 내 모임 감추기 / 일정에서는 달력 감추기 등)
=> Deploy: 릴리즈 버전4 업데이트 및 버전 불일치 버그 수정

golbang_jb/android/settings.gradle, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_result_full_score_card.dart, golbang_jb/pubspec.lock
- 엑셀 파일 생성 형식 변경 (Transpose 및 팀별 정렬 추가)
- Event Detail 페이지에 엑셀 파일 추출 버튼 추가
사진은 나중에 추가..
https://learntosurf.notion.site/Transpose-d8bb060258034f53ba2b880a3d878d39?pvs=4
=> Fix&Feat: 엑셀파일 Transpose 및 팀별 정렬 & Event Detail 페이지에 Excel 파일 추출 버튼 추가

golbang_jb/lib/main.dart, golbang_jb/lib/pages/home/splash_screen.dart, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/repoisitory/secure_storage.dart, golbang_jb/lib/services/auth_service.dart
- 자동 로그인 구현
- 한번 로그인하면 토큰 만료까지 계속 자동 로그인 (토큰 만료된 이후에도 정상동작 할지는 다시 체크해봐야할 듯..)
- 설정에서 로그아웃하면 자동로그인 풀림
=> Hotfix: 자동 로그인 구현

golbang_jb/android/app/build.gradle, golbang_jb/android/app/src/main/AndroidManifest.xml, golbang_jb/android/build.gradle, golbang_jb/android/gradle/wrapper/gradle-wrapper.properties, golbang_jb/android/settings.gradle, golbang_jb/lib/main.dart, golbang_jb/lib/pages/event/widgets/ranking_list.dart, golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/pages/logins/hi_screen.dart, golbang_jb/lib/pages/notification/notification_history_page.dart, golbang_jb/lib/pages/profile/statistics_page.dart, golbang_jb/pubspec.lock, golbang_jb/pubspec.yaml
- 회원가입&스코어카드 입력 쪽 문제 수정
- App Link 포함 환경 설정
=> Hotfix: QA에서 발생한 회원가입&스코어카드 입력 쪽 문제 수정 및 App Link 포함 환경 설정

golbang_jb/android/app/src/main/AndroidManifest.xml, golbang_jb/lib/main.dart
> ex) #이슈번호, #이슈번호
- 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 설명에 커밋 번호도 있다면 도움이 됩니다.
아래 내용 중 수정된 부분 위주로 작성해주세요! (수정되지 않는 부분은 지워주시면 됩니다)
이벤트 링크 클릭시 이벤트 상세 페이지로 이동 구현.
---
앱을 종료 후 앱을 실행하면 자동 로그인이 되지 않음.
다만 앱을 종료 후 링크를 클릭하면 자동 로그인이 유지..
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> 이벤트 링크 클릭시 이벤트 상세 페이지로 이동 구현.

golbang_jb/lib/pages/common/privacy_policy_page.dart, golbang_jb/pubspec.lock, golbang_jb/pubspec.yaml
1. 생일은 필수인데 선택으로 돼있어서 수정
2. 구글 콘솔 지침에 따라 회원탈퇴 절차 및 앱 개발자 표기
=> Docs: 개인정보 처리방침 내용 수정

golbang_jb/.gitignore, golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/services/club_service.dart
기존에는 이벤트 생성권한이 없는 모임도 보였어서, 
이벤트 생성하기 불편하였다. 그래서, 관리자인 모임만 보이도록 코드 수정하였습니다.
=> Fix: 이벤트 생성시 유저가 관리자인 모임만 보이도록 필터링

golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/widgets/sections/groups_section.dart, golbang_jb/pubspec.yaml
- 5eb74f384a3f3fbd0766a32959cee914300855d1: group_section 충돌난 부분 추가 제거
- b097ba76900ac56b51495699437051fb1e266141: 테스트 버전 업데이트
=> Hotfix: group_section 충돌난 부분 추가 제거

golbang_jb/ios/Podfile, golbang_jb/ios/Runner.xcodeproj/project.pbxproj, golbang_jb/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json, golbang_jb/ios/Runner/GoogleService-Info.plist, golbang_jb/ios/Runner/Info.plist, golbang_jb/lib/main.dart
=> hotfix: iOS FCM 토큰 초기 설정

golbang_jb/ios/Podfile.lock, golbang_jb/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, golbang_jb/ios/Runner/AppDelegate.swift
첨부한 이미지의 에러를 해결하기 위해 swift 파일에 구글맵 관련 설정 값을 추가하였습니다. (맥중범)
이전에 중범선배께서 올려주신 PR에 Xcode 설정 관련 PR( https://github.com/iNESlab/Golbang_FE/pull/109 )내용도 꼭 확인해주세요.
=> hotJB: iOS - googleMap SDK 관련 에러를 해결하기 위해 구글맵API 설정값 추가

golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/services/auth_service.dart
[fix: height 초기화 전에 렌더링되는 버그 수정](https://github.com/iNESlab/Golbang_FE/commit/417968610bfaf7adf6ef50354a8654cd15c764b5)
```
The following LateError was thrown building ScoreCardPage(dirty, state: _ScoreCardPageState#b2ca9):
LateInitializationError: Field 'width' has not been initialized.
```
스코어 카드페이지를 처음 열면, width, height초기화 전에 렌더링이되는 에러가 있어서,
수정하였습니다.
[docs: login은 dio를 안거치므로 log강화](https://github.com/iNESlab/Golbang_FE/commit/3d1314d62b49a721c09107db0d162f5fb3750ee6)
https 프로토콜 테스트 중 login에러 로그가 안떠서 추가했습니다
=> fix: height 초기화 전에 렌더링되는 버그 수정

golbang_jb/lib/models/club.dart, golbang_jb/lib/models/event.dart, golbang_jb/lib/models/member.dart, golbang_jb/lib/models/profile/member_profile.dart, golbang_jb/lib/models/update_event_participant.dart, golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/pages/group/group_create.dart, golbang_jb/lib/services/group_service.dart, golbang_jb/lib/utils/AllowNavigateNumbersFormatter.dart
- 스코어카드 화면 스코어 입력 오류 수정
- 마이너스(-) 값을 입력할 수 없던 문제 해결
- 스코어 입력 방식 개선
- 기존 값을 삭제하지 않고, 새로운 값을 바로 입력할 수 있도록 수정
- 새로운 값 입력 시 기존 스코어가 Hint Text로 표시되도록 변경
- 완료 버튼을 누르지 않고 다른 입력 필드를 선택해도 값이 정상적으로 반영되도록 개선
- 이벤트 상세 페이지 프로필 이미지 관련 이슈 해결
- 멤버 조회 페이지에 멤버를 추가할 수 있는 기능 추가 (In progress)
=> [Fix] 스코어 카드 입력 오류 수정 및 입력 방식 개선 & 이벤트 상세 페이지 이미지 관련 이슈 해결 & 멤버 추가 기능 추가중

golbang_jb/lib/models/group.dart, golbang_jb/lib/pages/community/admin_settings_page.dart, golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/community/member_settings_page.dart, golbang_jb/lib/services/club_service.dart
=> [Feat] 멤버추가 기능 및 레이아웃 업데이트

golbang_jb/lib/widgets/sections/community_member_dialog.dart
=> [Feat] 멤버추가 기능 및 레이아웃 업데이트 2

golbang_jb/lib/models/responseDTO/CourseResopnseDTO.dart, golbang_jb/lib/models/responseDTO/LocationResponseDTO.dart, golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/widgets/location_search_dialog.dart, golbang_jb/lib/pages/signup/additional_info.dart, golbang_jb/lib/pages/signup/signup.dart, golbang_jb/lib/pages/signup/widgets/calendar.dart, golbang_jb/lib/repoisitory/secure_storage.dart, golbang_jb/lib/services/event_service.dart
[Feat: 골프장 리스트 조회 API 연동](https://github.com/iNESlab/Golbang_FE/commit/30aaf4bd4d31a99ffc0549ca9fc5ee9d4899881c)
: 이건 아직 테스트가 안됐습니다......
[Refactor: 회원가입시, 생일은 캘린더에서 선택하도록 변경 및 print문 log로 변경](https://github.com/iNESlab/Golbang_FE/commit/a42e70b41699b863eaf8f070b70790022ef27492)
: `-` 자동완성시킬 경우, 생성은 되는데 지우는게 도저희 안되더라구요. 그래서 캘린더 선택으로 변경했습니다.
[Refactor: 회원을 꾹 눌렀을 때, 회색으로 누른 표시 뜨도록 수정 및 관리자 추방 메시지 추가 (+ print->log)](https://github.com/iNESlab/Golbang_FE/commit/a98e8a01a08ea608bc8904eb0b09d117ad0ff199)
: 눌렀을 때, 회색으로 터치감을 추가했습니다.
: 관리자만 꾹 누르면 퇴출할 수 있다는 안내를 추가했습니다.
꾹 눌러서 회색 표시되는건 너무 빨라서 못찍겠네요..
=> Refactor&Feat: 회원가입시 캘린더로 생년월일 입력, 멤버 추방(터치 시각효과 및 설명문 추가), 골프장 리스트 조회 API연동

golbang_jb/lib/pages/profile/statistics_page.dart
[feat(statistics): 연도별 통계 조회의 하드코딩된 2023, 2024를 제거하고, 드롭다운으로 연도를 선택할 수 있도록 기능 추가](https://github.com/iNESlab/Golbang_FE/commit/315409d01e65b4c0327b9e148ae5b1d6cd0d48e3), [refactor(statistics): 사용하지 않는 코드 제거](https://github.com/iNESlab/Golbang_FE/commit/113458d3ab83e484694929f8f1a4ffa0f3b463a2)
- 기존에는 "2024" "2023"으로 하드코딩되어 있었습니다.
- 2025 뿐만 아니라 앞으로를 위해서 현재 년도부터 2000년까지 드롭다운으로 선택할 수 있도록 기능을 추가하였습니다.
아래 코드를 추가하고, `_buildYearSelector` 를 새로 구현했습니다. (기존의`_buildYearButton`은 제거)
```dart
@override
void initState() {
super.initState();
// years 리스트 생성 (현재 연도 ~ 2000)
for (int i = DateTime.now().year; i>= 2000; i--) {
years.add('$i');
}
years.insert(0, '전체'); // 첫 번째 옵션으로 "전체" 추가
}
```
[design(statistics): 통계 화면 페이지 개선](https://github.com/iNESlab/Golbang_FE/commit/ddc6746a8bd86e64e839de42383074bd36182 …
=> Feat: 통계 연도별 조회할 수 있는 드롭다운 기능 추가, UI 개선

golbang_jb/lib/pages/signup/signup.dart, golbang_jb/lib/pages/signup/terms_agreement_page.dart, golbang_jb/lib/pages/signup/widgets/welcome_header_widget.dart
- **Before:** 
- 회원가입 시 화면이 작은 핸드폰의 경우, 약관동의 화면이 잘리는 문제가 발생했습니다.
- **After:**
- 약관동의 화면과 회원가입 1단계 화면을 반응형으로 UI를 수정했습니다.
- **세로로 중앙**에 위치하도록 설정했고, 하단 [다음] 버튼은 고정하였습니다.
> **Pixcel 2 (1080*1920)**
> **Pixcel 3(1080*2160)**
> **Pixcel 4(1080*2280)**
> **Pixcel 6(1080*2400)**
> 아이폰 12 mini : 1080 * 2340
> **Pixcel 7(1080*2400)**
---
- Xcode가 이이 상태로 멈춰있어서 정작 iPhone 12 mini, iPhone SE에서는 테스트를 못했습니다..! 테스트가 필요합니다
=> design(signup): 회원가입을 위한 약관동의 화면, 회원가입 1단계 화면 반응형으로 디자인 보완

golbang_jb/lib/pages/club/club_edit_page.dart
- 기존에 club, user가 read라서 null 인식시 발생한 에러
- didChangeDependencies 내부에서 watch로 변경
=> hotix: 모임 및 관리자 변경 페이지 구독 에러

golbang_jb/lib/pages/club/club_edit_page.dart, golbang_jb/lib/pages/community/admin_settings_page.dart
- 기존에 controller가 late로 notnullable로 돼있어서 초기값을 선언했습니다.
로딩시간이 좀 걸려서
향후, 이전 PR에서 수정한 형태로 다시 리펙토링 진행예정입니다.
https://github.com/iNESlab/Golbang_FE/pull/144/commits/a60f5105f7a332fd5029b06f2c61f75f604d99b7#diff-c02c7a55ed7ea569f4cd7f5c2fdeddd2f354f8a1fdeba2bc53b567610d289653
=> Fix: 모임 수정 페이지 provider null에러 임시 조치

golbang_jb/android/app/src/main/AndroidManifest.xml, golbang_jb/android/app/src/main/kotlin/com/example/golbang/MainActivity.kt, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/repoisitory/secure_storage.dart, golbang_jb/lib/services/auth_service.dart, golbang_jb/lib/services/bio_auth.dart, golbang_jb/pubspec.lock, golbang_jb/pubspec.yaml
[feat: 생체인식 로그인 기능 구현 (안드로이드)](https://github.com/iNESlab/Golbang_FE/commit/8c83af9d8748a200998c45caa26ffc0511b10c55) 
- ios는 따로 테스트 해봐야 함.
---
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 새로운 패키지 추가 (pubspec.get 해야 합니다)
=> feat: 생체인식 로그인 기능 구현 (안드로이드)

golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/logins/login.dart
- 중범선배가 작업하신 게임 진행중에는 엑셀 추출시 15분 텀이 발생할 수 있다는 경고 모달
- 보안을 위해, 비밀번호는 로그인 페이지가 불러올 때 부르지 않고, 생체인증을 해야 불러오도록 변경
- 배포 앱 버전 수정
=> feat&refactor: 엑셀 스코어 추출 경고 모달, 로그인 로직 변경

golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/services/participant_service.dart, golbang_jb/lib/utils/safe_dio_call.dart
- API 에러 메시지 헬퍼 함수 구현
- API 실패 모달창 추가
Service 파일에서 API 사용시 safeDioCall을 이용하여 에러를 던지고
페이지에서 이 에러를 modal창에 띄우면 됩니다.
=> refactor: API 에러 세분화

golbang_jb/lib/models/create_event.dart, golbang_jb/lib/models/event.dart, golbang_jb/lib/models/participant.dart, golbang_jb/lib/models/responseDTO/GolfClubResponseDTO.dart, golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_create2.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/event_update2.dart, golbang_jb/lib/pages/event/widgets/course_selection_dialog.dart, golbang_jb/lib/pages/home/home_page.dart, golbang_jb/lib/services/club_service.dart, golbang_jb/lib/widgets/sections/upcoming_events.dart
- 코스 선택 UI 생성
- 이벤트 생성 시 golf_course_id, golf_club_id를 같이 보냄
- 이벤트 디테일에서 코스 정보는 하나만, 골프장 이름도 같이 보여주게 변경
- 이벤트 생성 시 site가 삭제되었는데 다시 필요할 듯?
- 업커밍 이벤트는 오늘까지의 일정만 보이게 필터링함
=> [Feat]업커밍 이벤트 차순 수정 및 이벤트 생성에 클럽 및 코스 아이디 추가

golbang_jb/lib/pages/game/overall_score_page.dart, golbang_jb/lib/pages/game/score_button_pad.dart, golbang_jb/lib/pages/game/score_card_page.dart, golbang_jb/lib/pages/home/home_page.dart
- 비우기 로직 적용
- 전체 스코어 카드에서 사용자가 자기 점수를 한번도 입력안했을 시 나오는 안내메세지 수정
- 홈화면 다가오는 일정 개수 불일치 문제 해결
=> [Fix] 다가오는 일정 개수 & 전체스코어카드 안내메세지 & 비우기 로직 수정

golbang_jb/lib/services/participant_service.dart
=> [Fix] 점수 비웠을 때 202 코드 대응

golbang_jb/lib/models/event.dart, golbang_jb/lib/models/member.dart, golbang_jb/lib/models/participant.dart, golbang_jb/lib/models/profile/member_profile.dart, golbang_jb/lib/models/update_event_participant.dart, golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/event/event_detail.dart, golbang_jb/lib/pages/event/event_result_full_score_card.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/widgets/no_api_participant_dialog.dart, golbang_jb/lib/pages/event/widgets/participant_dialog.dart, golbang_jb/lib/widgets/sections/community_member_dialog.dart, golbang_jb/lib/widgets/sections/member_dialog.dart, golbang_jb/lib/widgets/sections/show_email_recipient_dialog.dart, golbang_jb/lib/widgets/sections/user_dialog.dart
[chore: print -> log 변환, member 모델 email 필드 추가](https://github.com/iNESlab/Golbang_FE/commit/b6ce2171a5bfa0b05da0c0bdd7ee840349268c37)
[feat: 이메일 수신 선택창 생성 및 적용](https://github.com/iNESlab/Golbang_FE/commit/1c7ac93bf27f953b88ca56fba0a49a6f009ca76f)
[feat: club member 초대시 userId로 검색 가능하게 변경](https://github.com/iNESlab/Golbang_FE/commit/cb39a064b1710ecea7beba7c109a362f276fc723) 
- 신규 초대시에만 Id 검색하는게 좋을거 같음
- 이벤트 참가자 검색은 기존 유지(Id가 서버에서 안옴)
- 멤버 -> 관리자 업데이트시에도 Id 검색은 되나 마찬가지로 unknownId임
<table>
<tr>
<td><strong>1. 이메일 수신자 선택</strong><br><img width="300" src="https://github.com/user-attachments/assets/faf6f194-d12d-47ea-b50b-eaa7903007e4" /></td>
<td><strong>2. ID 검색 초기 화면</strong><br><img width="300" src="https://github.com/user-attachments/assets/f02b7c74-674c-4143-a3db-1 …
=> feat: 이메일 수신자 선택 모달창 + 모임 초대시, ID 검색 가능 

golbang_jb/assets/images/google_logo.png, golbang_jb/lib/app/main_scaffold.dart, golbang_jb/lib/app/routes/auth_routes.dart, golbang_jb/lib/app/routes/club_routes.dart, golbang_jb/lib/app/routes/event_routes.dart, golbang_jb/lib/global/PrivateClient.dart, golbang_jb/lib/global/PublicClient.dart, golbang_jb/lib/models/chat_room.dart, golbang_jb/lib/models/profile/club_profile.dart, golbang_jb/lib/pages/chat/club_chat_page.dart, golbang_jb/lib/pages/community/community_main.dart, golbang_jb/lib/pages/event/detail/event_detail_bottom.dart, golbang_jb/lib/pages/event/event_main.dart, golbang_jb/lib/pages/logins/login.dart, golbang_jb/lib/pages/logins/widgets/social_login_widgets.dart, golbang_jb/lib/pages/signup/additional_info.dart, golbang_jb/lib/pages/signup/signup.dart, golbang_jb/lib/pages/signup/terms_agreement_page.dart, golbang_jb/lib/provider/chat/chat_provider.dart, golbang_jb/lib/provider/participant/participant_state_provider.dart, golbang_jb/lib/providers/global_radio_provider.dart, golbang_jb/lib/services/chat_service.dart, golbang_jb/lib/services/event_service.dart, golbang_jb/lib/services/google_auth_service.dart, golbang_jb/lib/services/rtmp_radio_service.dart, golbang_jb/lib/services/stomp_chat_service.dart, golbang_jb/lib/services/synchronized_radio_service.dart, golbang_jb/lib/widgets/global_radio_player.dart, golbang_jb/lib/widgets/google_sign_in_button.dart, golbang_jb/pubspec.yaml
=> Feat: 소셜 로그인 & 채팅방 & 중계시스템 잔재 & 이모저모

golbang_jb/lib/app/routes/club_routes.dart, golbang_jb/lib/global/PrivateClient.dart, golbang_jb/lib/models/event.dart, golbang_jb/lib/models/member.dart, golbang_jb/lib/models/profile/member_profile.dart, golbang_jb/lib/models/update_event_participant.dart, golbang_jb/lib/pages/club/club_main.dart, golbang_jb/lib/pages/club/club_search_page.dart, golbang_jb/lib/pages/community/community_main.dart, golbang_jb/lib/pages/community/member_list_page.dart, golbang_jb/lib/pages/community/member_settings_page.dart, golbang_jb/lib/pages/event/detail/event_detail_appbar.dart, golbang_jb/lib/pages/event/detail/event_detail_body.dart, golbang_jb/lib/pages/event/detail/event_detail_page.dart, golbang_jb/lib/pages/event/detail/widget/event_header_section.dart, golbang_jb/lib/pages/event/event_create1.dart, golbang_jb/lib/pages/event/event_update1.dart, golbang_jb/lib/pages/event/widgets/participant_dialog.dart, golbang_jb/lib/pages/profile/user_info_page.dart, golbang_jb/lib/provider/club/club_state_provider.dart, golbang_jb/lib/services/club_service.dart
1. minus handicap : -50 ~ 100 으로 수정
2. End game logic fix: 반만 고침(다 고친게 아님)
3. Group search, apply and approval (see next page): 일단 혼자했을 때는 잘 됨 
=> 알람이 없어서 편의성이 떨어지는 부분 존재 
4. 일반 유저는 클럽 설정 페이지 들어갈 경우 Go 라우터 에러 뜨는 버그 수정
2번의 경우, 
지금은 이벤트 상세 내에서의 UI 변경은 되도록 함.
하지만, 이벤트 메인으로 이동할 경우 기존 조회값 때문에 종료가 안된 것처럼 보여짐.
=> 이벤트 전체를 상태관리로 다뤄서 해결해야하는데, 테스트를 많이 해야하는 도메인이라(1주일 내에는 못함)
=> 반만 고치고 반은 그대로인 상태
| 1. 홈 | 2. 검색/신청 | 3. 승인 대기 | 4. 승인 후 |
|---------|---------|--------------|--------------|
| ![001](https://github.com/user-attachments/assets/de6368b6-82fa-4b48-9f4c-1612b260fb1a) |![002](https://github.com/user-attachments/assets/0f159121-668d-4c61-8b15-742c5dcaa171  ) | ![003](https://github.com/user-attachments/assets/11e83304-7eaa-4c3b-b77b-924b7adc3e3a) | ![004]( …
=> Feat: 모임 신청/승인 & 게임 종료 버그 수정
